/*
Deployment script for STAM DATABASE FOR VISUAL STUDIO

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Achitofel"
:setvar DefaultFilePrefix "STAM DATABASE FOR VISUAL STUDIO"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Schema [History]...';


GO
CREATE SCHEMA [History]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating Table [dbo].[Addresses_RelativesEmployees]...';


GO
CREATE TABLE [dbo].[Addresses_RelativesEmployees] (
    [ID]            INT            IDENTITY (1, 1) NOT NULL,
    [AddressType]   INT            NOT NULL,
    [Street]        NVARCHAR (50)  NOT NULL,
    [House#]        NVARCHAR (50)  NOT NULL,
    [Unit_Flat#]    NVARCHAR (10)  NULL,
    [City]          NVARCHAR (50)  NOT NULL,
    [Region]        NVARCHAR (50)  NULL,
    [Postcode]      NVARCHAR (50)  NULL,
    [Country]       NVARCHAR (50)  NOT NULL,
    [NotesDelivery] NVARCHAR (200) NULL,
    [HomePhone]     NVARCHAR (50)  NULL
);


GO
PRINT N'Creating Table [dbo].[AddressTypeC]...';


GO
CREATE TABLE [dbo].[AddressTypeC] (
    [AddressTypeID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]         NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([AddressTypeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Benefits_Bonuses]...';


GO
CREATE TABLE [dbo].[Benefits_Bonuses] (
    [SocialCode]        INT            IDENTITY (1, 1) NOT NULL,
    [BenefitName]       NVARCHAR (200) NOT NULL,
    [PercentageBenefit] FLOAT (53)     NOT NULL,
    [PercentageSalary]  FLOAT (53)     NOT NULL,
    [SalaryCode]        INT            NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Benefits_BonusesC]...';


GO
CREATE TABLE [dbo].[Benefits_BonusesC] (
    [SalaryCodeID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]        NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([SalaryCodeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[BranchesCustomers]...';


GO
CREATE TABLE [dbo].[BranchesCustomers] (
    [CustomerID]        INT            NOT NULL,
    [CustomerBranchID]  INT            IDENTITY (1, 1) NOT NULL,
    [Street]            NVARCHAR (50)  NULL,
    [House#]            NVARCHAR (50)  NULL,
    [Unit_Flat#]        NVARCHAR (10)  NULL,
    [City]              NVARCHAR (50)  NULL,
    [Region]            NVARCHAR (50)  NULL,
    [PostCode]          NVARCHAR (50)  NULL,
    [Country]           NVARCHAR (50)  NULL,
    [DistanceAchitofel] NVARCHAR (200) NOT NULL,
    [NotesDelivery]     NVARCHAR (200) NULL,
    [HomePhone]         NVARCHAR (25)  NULL,
    [Fax]               NVARCHAR (25)  NULL
);


GO
PRINT N'Creating Table [dbo].[CompanySizeC]...';


GO
CREATE TABLE [dbo].[CompanySizeC] (
    [CompanySizeID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]         NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([CompanySizeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Currency_Exchange_Rates]...';


GO
CREATE TABLE [dbo].[Currency_Exchange_Rates] (
    [CurrencyType]  INT   NOT NULL,
    [ExchangeValue] MONEY NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Customers]...';


GO
CREATE TABLE [dbo].[Customers] (
    [CustomerID]  INT           IDENTITY (1, 1) NOT NULL,
    [CompanyName] NVARCHAR (50) NOT NULL,
    [CompanySize] INT           NOT NULL,
    [Industry]    NVARCHAR (50) NULL,
    [Nationality] INT           NOT NULL,
    [TeamID]      INT           NOT NULL,
    [BlackList]   INT           NOT NULL
);


GO
PRINT N'Creating Table [dbo].[DecisionHRC]...';


GO
CREATE TABLE [dbo].[DecisionHRC] (
    [DecisionHRID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]        NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([DecisionHRID] ASC)
);


GO
PRINT N'Creating Table [dbo].[DecisionMC]...';


GO
CREATE TABLE [dbo].[DecisionMC] (
    [DecisionMID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]       NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([DecisionMID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Employees]...';


GO
CREATE TABLE [dbo].[Employees] (
    [EmployeeID]         INT                                                IDENTITY (1, 1) NOT NULL,
    [ID]                 CHAR (9)                                           NOT NULL,
    [Title]              INT                                                NOT NULL,
    [LastName]           NVARCHAR (50)                                      NOT NULL,
    [FirstName]          NVARCHAR (50)                                      NOT NULL,
    [TitleOfCourtesy]    INT                                                NOT NULL,
    [Gender]             INT                                                NOT NULL,
    [Status_]            INT                                                NOT NULL,
    [BirthDate]          DATETIME                                           NOT NULL,
    [HireDate]           DATETIME                                           NOT NULL,
    [EndDate]            DATETIME                                           NULL,
    [SDailyWHours]       FLOAT (53)                                         NOT NULL,
    [SalaryFirstBasic]   MONEY                                              NOT NULL,
    [SalaryCurrentBasic] MONEY                                              NOT NULL,
    [MobilePrivate]      NVARCHAR (25)                                      NULL,
    [MobileBusiness]     NVARCHAR (25)                                      NOT NULL,
    [EmailPrivate]       NVARCHAR (50)                                      NULL,
    [EmailBusiness]      NVARCHAR (50)                                      NOT NULL,
    [Extension]          NVARCHAR (6)                                       NULL,
    [ReportsTo]          INT                                                NULL,
    [Notes]              NVARCHAR (200)                                     NULL,
    [ValidFrom]          DATETIME2 (7) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
    [ValidTo]            DATETIME2 (7) GENERATED ALWAYS AS ROW END HIDDEN   NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
);


GO
PRINT N'Creating Table [dbo].[EmploymentCost]...';


GO
CREATE TABLE [dbo].[EmploymentCost] (
    [EmployeeID]         INT      NOT NULL,
    [CostDate]           DATETIME NOT NULL,
    [SalaryCurrentBasic] MONEY    NOT NULL,
    [Benefits]           INT      NOT NULL,
    [OverTime]           INT      NULL,
    [ManagementBonus]    INT      NULL,
    [Travel]             INT      NULL,
    [VacationDays]       INT      NOT NULL,
    [Tax]                INT      NULL
);


GO
PRINT N'Creating Table [dbo].[ExecutivesDetailsCustomers]...';


GO
CREATE TABLE [dbo].[ExecutivesDetailsCustomers] (
    [CustomerManagerID] INT            IDENTITY (1, 1) NOT NULL,
    [Relationship]      NVARCHAR (10)  NOT NULL,
    [FirstName]         NVARCHAR (50)  NOT NULL,
    [LastName]          NVARCHAR (50)  NOT NULL,
    [Birthdate]         DATETIME       NOT NULL,
    [Street]            NVARCHAR (50)  NOT NULL,
    [House#]            NVARCHAR (50)  NOT NULL,
    [Unit_Flat#]        NVARCHAR (10)  NULL,
    [City]              NVARCHAR (50)  NOT NULL,
    [Region]            NVARCHAR (50)  NULL,
    [Postcode]          NVARCHAR (50)  NULL,
    [Country]           NVARCHAR (50)  NOT NULL,
    [NotesDelivery]     NVARCHAR (200) NULL,
    [CakeFlavor]        NVARCHAR (100) NOT NULL,
    [HomePhone]         NVARCHAR (25)  NOT NULL
);


GO
PRINT N'Creating Table [dbo].[GenderC]...';


GO
CREATE TABLE [dbo].[GenderC] (
    [GenderID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]    NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([GenderID] ASC)
);


GO
PRINT N'Creating Table [dbo].[HoursReportEmployees]...';


GO
CREATE TABLE [dbo].[HoursReportEmployees] (
    [ProjectID]        INT      NOT NULL,
    [EmployeeID]       INT      NOT NULL,
    [ReportDate]       DATETIME NOT NULL,
    [StartHour]        DATETIME NOT NULL,
    [EndHour]          DATETIME NOT NULL,
    [CustomerBranchID] INT      NOT NULL
);


GO
PRINT N'Creating Table [dbo].[HRHearing]...';


GO
CREATE TABLE [dbo].[HRHearing] (
    [EmployeeID]               INT            NOT NULL,
    [HearingDate]              DATETIME       NOT NULL,
    [Details]                  NVARCHAR (100) NOT NULL,
    [Decision]                 INT            NOT NULL,
    [Warning#]                 INT            NULL,
    [Notes]                    NVARCHAR (100) NULL,
    [DateLetterSocialSecurity] DATETIME       NULL
);


GO
PRINT N'Creating Table [dbo].[Invoices]...';


GO
CREATE TABLE [dbo].[Invoices] (
    [InvoiceNumber] INT            IDENTITY (1, 1) NOT NULL,
    [CustomerID]    INT            NOT NULL,
    [DateIssued]    DATETIME       NOT NULL,
    [BlackListFee]  FLOAT (53)     NULL,
    [DueDate]       DATETIME       NOT NULL,
    [DatePaid]      DATETIME       NULL,
    [TotalFees]     MONEY          NOT NULL,
    [Discount]      FLOAT (53)     NULL,
    [AmountPayable] MONEY          NOT NULL,
    [Notes]         NVARCHAR (200) NULL
);


GO
PRINT N'Creating Table [dbo].[ManagerHearing]...';


GO
CREATE TABLE [dbo].[ManagerHearing] (
    [EmployeeID]  INT            NOT NULL,
    [HearingDate] DATETIME       NOT NULL,
    [Details]     NVARCHAR (200) NOT NULL,
    [Decision]    INT            NOT NULL,
    [ReportToHR]  BINARY (50)    NULL
);


GO
PRINT N'Creating Table [dbo].[Managers_Customers]...';


GO
CREATE TABLE [dbo].[Managers_Customers] (
    [CustomerID]        INT            NOT NULL,
    [CustomerManagerID] INT            IDENTITY (1, 1) NOT NULL,
    [ManagerType]       INT            NOT NULL,
    [LastName]          NVARCHAR (50)  NOT NULL,
    [FirstName]         NVARCHAR (50)  NOT NULL,
    [TitleOfCourtesy]   INT            NOT NULL,
    [Gender]            INT            NOT NULL,
    [BirthDate]         DATETIME       NOT NULL,
    [CakeFlavor]        NVARCHAR (100) NOT NULL,
    [Notes]             NVARCHAR (200) NULL,
    [Street]            NVARCHAR (50)  NOT NULL,
    [House#]            NVARCHAR (50)  NOT NULL,
    [Unit_Flat#]        NVARCHAR (10)  NULL,
    [City]              NVARCHAR (50)  NOT NULL,
    [Region]            NVARCHAR (50)  NULL,
    [Postcode]          NVARCHAR (50)  NULL,
    [Country]           NVARCHAR (50)  NOT NULL,
    [NotesDelivery]     NVARCHAR (200) NULL,
    [HomePhone]         NVARCHAR (50)  NULL
);


GO
PRINT N'Creating Table [dbo].[Managers_CustomersC]...';


GO
CREATE TABLE [dbo].[Managers_CustomersC] (
    [ManagerTypeID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]         NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([ManagerTypeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Metrics]...';


GO
CREATE TABLE [dbo].[Metrics] (
    [Code]          INT            IDENTITY (1, 1) NOT NULL,
    [ParameterType] INT            NOT NULL,
    [Details]       NVARCHAR (200) NOT NULL,
    [ValuePoint]    FLOAT (53)     NOT NULL,
    [StartDate]     DATETIME       NOT NULL,
    [EndDate]       DATETIME       NOT NULL
);


GO
PRINT N'Creating Table [dbo].[NationalityC]...';


GO
CREATE TABLE [dbo].[NationalityC] (
    [NationalityID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]         NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([NationalityID] ASC)
);


GO
PRINT N'Creating Table [dbo].[ParameterTypeC]...';


GO
CREATE TABLE [dbo].[ParameterTypeC] (
    [ParameterTypeID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]           NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([ParameterTypeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[ProjectEmployees]...';


GO
CREATE TABLE [dbo].[ProjectEmployees] (
    [EmployeeID]        INT NOT NULL,
    [ProjectID]         INT NOT NULL,
    [ProjectRateHourly] INT NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Projects]...';


GO
CREATE TABLE [dbo].[Projects] (
    [ProjectID]         INT            IDENTITY (1, 1) NOT NULL,
    [CustomerManagerID] INT            NOT NULL,
    [CustomerID]        INT            NOT NULL,
    [ProjectName]       NVARCHAR (50)  NOT NULL,
    [StartDate]         DATETIME       NOT NULL,
    [EndDateEstimate]   DATETIME       NOT NULL,
    [EndDateActual]     DATETIME       NOT NULL,
    [Description_]      NVARCHAR (200) NOT NULL,
    [BlackList]         INT            NOT NULL,
    [NotesBL]           NVARCHAR (200) NOT NULL
);


GO
PRINT N'Creating Table [dbo].[RelationshipC]...';


GO
CREATE TABLE [dbo].[RelationshipC] (
    [RelationshipID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]          NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([RelationshipID] ASC)
);


GO
PRINT N'Creating Table [dbo].[RelativesEmployees]...';


GO
CREATE TABLE [dbo].[RelativesEmployees] (
    [EmployeeID]      INT           NOT NULL,
    [ID]              CHAR (9)      NOT NULL,
    [Relationship]    INT           NOT NULL,
    [LastName]        NVARCHAR (35) NOT NULL,
    [FirstName]       NVARCHAR (35) NOT NULL,
    [TitleOfCourtesy] INT           NOT NULL,
    [BirthDate]       DATETIME      NOT NULL,
    [Gender]          INT           NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Status_C]...';


GO
CREATE TABLE [dbo].[Status_C] (
    [Status_ID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]     NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([Status_ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Teams]...';


GO
CREATE TABLE [dbo].[Teams] (
    [TeamID]     INT IDENTITY (1, 1) NOT NULL,
    [EmployeeID] INT NOT NULL
);


GO
PRINT N'Creating Table [dbo].[TitleC]...';


GO
CREATE TABLE [dbo].[TitleC] (
    [TitleID] INT           IDENTITY (1, 1) NOT NULL,
    [Value]   NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([TitleID] ASC)
);


GO
PRINT N'Creating Table [dbo].[TitleOfCourtesyC]...';


GO
CREATE TABLE [dbo].[TitleOfCourtesyC] (
    [TitleOfCourtesy] INT           IDENTITY (1, 1) NOT NULL,
    [Value]           NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([TitleOfCourtesy] ASC)
);


GO
PRINT N'Creating Default Constraint [dbo].[DF_SysStart]...';


GO
ALTER TABLE [dbo].[Employees]
    ADD CONSTRAINT [DF_SysStart] DEFAULT (sysutcdatetime()) FOR [ValidFrom];


GO
PRINT N'Creating Default Constraint [dbo].[DF_SysEnd]...';


GO
ALTER TABLE [dbo].[Employees]
    ADD CONSTRAINT [DF_SysEnd] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999')) FOR [ValidTo];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[HoursReportEmployees]...';


GO
ALTER TABLE [dbo].[HoursReportEmployees]
    ADD DEFAULT (getdate()) FOR [ReportDate];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Invoices]...';


GO
ALTER TABLE [dbo].[Invoices]
    ADD DEFAULT ((0)) FOR [BlackListFee];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Invoices]...';


GO
ALTER TABLE [dbo].[Invoices]
    ADD DEFAULT ((0)) FOR [Discount];


GO
PRINT N'Creating Check Constraint [dbo].[HoursReportEmployees_endhour]...';


GO
ALTER TABLE [dbo].[HoursReportEmployees] WITH NOCHECK
    ADD CONSTRAINT [HoursReportEmployees_endhour] CHECK ([endhour]>[starthour]);


GO
PRINT N'Creating Check Constraint [dbo].[Managers_Customers_AGE_18]...';


GO
ALTER TABLE [dbo].[Managers_Customers] WITH NOCHECK
    ADD CONSTRAINT [Managers_Customers_AGE_18] CHECK (datediff(year,[birthdate],getdate())>=(18));


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[HoursReportEmployees] WITH CHECK CHECK CONSTRAINT [HoursReportEmployees_endhour];

ALTER TABLE [dbo].[Managers_Customers] WITH CHECK CHECK CONSTRAINT [Managers_Customers_AGE_18];


GO
PRINT N'Update complete.';


GO
